[tools]
"http:tailwindcss" = { version = "4.1.17", url = "https://github.com/tailwindlabs/tailwindcss/releases/download/v{{version}}/tailwindcss-linux-{{arch()}}" }
just = "latest"
sqlite3def = "latest"
uv = "latest"
