[project]
name = "vvzapi"
version = "1.3.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.17.0",
    "fastapi[standard]>=0.119.0",
    "jinja2>=3.1.6",
    "jinja2-htmlmin>=1.0.1",
    "jinja2-pluralize>=0.3.0",
    "pydantic>=2.12.0",
    "pydantic-settings>=2.11.0",
    "rapidfuzz>=3.14.3",
    "scrapy>=2.13.3",
    "sqlmodel>=0.0.27",
    "toml>=0.10.2",
]

[dependency-groups]
dev = ["basedpyright>=1.37.0", "pyrefly>=0.47.0"]

[tool.basedpyright]
typeCheckingMode = "standard"
include = ["api", "scraper"]
reportDeprecated = false
reportUninitializedInstanceVariable = false

[tool.pyrefly.errors]
deprecated = false
